### ISSUE TITLE
Plastic Simulation cone example is broken

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/Adhesion#63]
We need to replace LinearizeCore Potential by .linearize_core in make_system

**Comment by sannant** [comment]
WIP in https://github.com/ContactEngineering/Adhesion/tree/bug/fix_adhesion_examples

**Comment by sitangshugk95** [comment]
It doesn't look like changing to .linearize_core in make_system solves the issue - 
![Screenshot from 2022-12-09 19-04-05](https://user-images.githubusercontent.com/108830413/206820898-08b2cc85-7bbd-4aa0-8de6-de9a2e4d6652.png)

What was this suggested modification based on? Is there anything else that we can try? I can do the necessary changes and submit a PR.

**Comment by sannant** [comment]
Sorry repaired it here: 
https://github.com/ContactEngineering/Adhesion/pull/69

**Comment by sannant** [comment]
Fixed
