### ISSUE TITLE
Adhesive Plastic Simulation Cone not working with PowerLaw or Exponential interactions

### ISSUE THREAD

**Issue by sitangshugk95** [ContactEngineering/Adhesion#78]
I tried to use a PowerLaw interaction instead of LJ82 (to see if they both give the same results), but I get the following error:
![image](https://user-images.githubusercontent.com/108830413/212180626-750f7bef-c55e-4b2e-9be7-7cf864b5ff56.png)

The only changes made from the example file are encircled below:
![image](https://user-images.githubusercontent.com/108830413/212180811-08c671e2-07d4-475d-adea-8cfcda809112.png)

Is this an error in the source code, or is there something wrong in how I am implementing it?

**Comment by sitangshugk95** [comment]
@sannant

**Comment by sitangshugk95** [comment]
Error also when Exponential is used (albeit different error message):

![image](https://user-images.githubusercontent.com/108830413/212187843-713ba536-c4de-4814-aca3-298fbae89dd2.png)

**Comment by sannant** [comment]
The exponential and Powerlaw potential do not include repulsion and are not meant to be used in combination with `linearize_core` (which is used to implement plasticity).

Ideally, we should check whether the potential has a repulsion and throw a more verbose error in linearize_core, but that is not a priority.
