### ISSUE TITLE
netCDF can't find mpi4py when installing on CI

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/Adhesion#95]
https://github.com/ContactEngineering/Adhesion/actions/runs/6312962459/job/17144730578

**Comment by sannant** [comment]
@pastewka any idea ? The problem should also arrise on the other repositories. 

The CI of ContactMechanics fails as well though...

**Comment by pastewka** [comment]
I don't know what this is. Please disable MPI in CI for now. (I did this for SurfaceTopography, will need to look into this when I have time.)
